### ISSUE TITLE
Git parameters superfluous when image is hard coded

### ISSUE THREAD

**Issue by geod** [awslabs/ecs-refarch-continuous-deployment#27]
Hi,

Template very useful Thanks. 

One issue when trying to re-use

1. [ecs-refarch-continuous-deployment.yaml](https://github.com/awslabs/ecs-refarch-continuous-deployment/blob/master/ecs-refarch-continuous-deployment.yaml) has a bunch of parameters to supply your own repository. But .... within [templates/service.yaml](https://github.com/awslabs/ecs-refarch-continuous-deployment/blob/master/templates/service.yaml) the amazon image is hard coded. When you switch to providing your own github project as parameters it actually has no effect (the amazon namespace is universally available in docker-hub. So what happens is you build your own project then use the amazon image at the last stage =) )

```
ContainerDefinitions:
        - Name: simple-app
          Image: amazon/amazon-ecs-sample
          EntryPoint:
```

I think it needs to be a parameter

2. Second suggestion is not to override the entry point as part of the task def and allow the entry point provided as part of docker image to run by default

G
