### ISSUE TITLE
Deploy ECS FileName syntax

### ISSUE THREAD

**Issue by froilan** [awslabs/ecs-refarch-continuous-deployment#30]
Just a question with regards to the images.json syntax.
I'm struggling to find any documentation with regards to it. 

``` yaml
Configuration:
                ClusterName: !Ref Cluster
                ServiceName: !Ref Service
                FileName: images.json
```

Basing on this, I assume that valid keys are name and imageUri. Is that it, or are there others?
If you don't mind, can you share a link on any documentation?
```
printf '[{"name":"simple-app","imageUri":"%s"}]' "$IMAGE_URI" > images.json
```
Great templates, really helpful btw..
